name: plantie
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  curved_labeled_navigation_bar: ^2.0.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flip_card: ^0.7.0
  flutter_svg: ^2.0.5
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  camera: ^0.11.0
  path_provider: ^2.1.3
  path: ^1.9.0
  tflite_flutter: ^0.10.4
  image: ^3.0.1
  image_picker: ^1.1.1
  geolocator: ^12.0.0
  url_launcher: ^6.2.6
  flutter_image_compress: ^2.3.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/ml/
  uses-material-design: true
