// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_9z9HQHPhMK2SSca4jGfv7y8GzFQTZ-4',
    appId: '1:404741528477:android:4b4c41bd498920a3662d74',
    messagingSenderId: '404741528477',
    projectId: 'plantie-8fb24',
    storageBucket: 'plantie-8fb24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB40XXbzBpFGJagXVret2VP2qV6Pc4cDI0',
    appId: '1:404741528477:ios:50ff43cc55b0b407662d74',
    messagingSenderId: '404741528477',
    projectId: 'plantie-8fb24',
    storageBucket: 'plantie-8fb24.appspot.com',
    androidClientId: '404741528477-9j52rbb6kecutehq1pauqgkdo78s3dv8.apps.googleusercontent.com',
    iosClientId: '404741528477-7kcte4r8smbg88045vd97t8hti8fve8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantie',
  );
}
